Name: LogConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Energy_Log_Interval
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Energy_Log_Mode
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_of_Use_Log_AutoLog_Setting
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Off_Peak_Days
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: MID_Peak_AM_Hours
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: MID_Peak_PM_Hours
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: ON_Peak_AM_Hours
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: ON_Peak_PM_hours
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Load_Factor_log_AutoLog_Setting
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N15:9"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
