Name: UserConfigurableTableResults
Type: FolderType
Children:
- Name: User_selected_Parameter_1
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_2
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_3
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_4
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_5
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_6
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_7
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_8
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_9
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_10
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:9"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_11
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:10"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_12
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:11"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_13
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:12"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_14
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:13"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_15
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:14"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: User_selected_Parameter_16
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F9:15"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
