Name: UserConfigurableTableSetup
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_1
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_2
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_3
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_4
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_5
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_6
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_7
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_8
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_9
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:9"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_10
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:10"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_11
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:11"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_12
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:12"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_13
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:13"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_14
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:14"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_15
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:15"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Selection_for_Parameter_16
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N44:16"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
