Name: SecurityPolicyConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Hardware_Configuration_Lock
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Communication_Port_Disable
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Web_Page_Disable
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: FTP_Port_Disable
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Flash_Update_Disable_ConfigurationLock
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Flash_Update_Disable_Security_Active
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: HTTPS_Enable
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: FTPS_Enable
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N45:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
