Name: EthernetConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: IP_Address_Byte_a_aaa_xxx_xxx_xxx
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: IP_Address_Byte_b_xxx_bbb_xxx_xxx
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: IP_Address_Byte_c_xxx_xxx_ccc_xxx
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: IP_Address_Byte_d_xxx_xxx_xxx_ddd
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Subnet_Mask_Byte_a
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Subnet_Mask_Byte_b
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Subnet_Mask_Byte_c
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Subnet_Mask_Byte_d
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Gateway_IP_Address_Byte_a
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:9"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Gateway_IP_Address_Byte_b
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:10"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Gateway_IP_Address_Byte_c
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:11"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Gateway_IP_Address_Byte_d
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:12"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: SNTP_Mode_Select
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:13"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: SNTP_Update_Interval
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:14"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Zone_Select
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:15"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Server_IP_AddressByte_a
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:16"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Server_IP_AddressByte_b
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:17"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Server_IP_AddressByte_c
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:18"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Server_IP_AddressByte_d
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:19"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Demand_Broadcast_MasterSelect
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:20"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Broadcast_Port_Number
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:21"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: IP_Address_Obtain
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N13:22"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
