Name: AnalogInputConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Voltage_Mode
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: PT_Primary
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: PT_Secondary
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: CT_Primary
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: System_PF_Setting
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F10:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
