Name: AdvancedConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: New_TablePassword
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Metering_ResultAveraging
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Log_Status_InputChanges
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Use_DaylightSaving_Correction
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Daylight_SavingMonth_Week_Day_Start
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Hour_of_Day_Start
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Return_fromDaylight_SavingMonth_Week_Day
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Hour_of_Day_End
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:8"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: KYZ_Solid_StateOutputParameter
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:9"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: KYZ_Solid_StateOutput_Scale
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:10"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: KYZ_PulseDuration_Setting
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:11"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Status_Input_1Input_Scale
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:12"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Status_Input_2Input_Scale
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:13"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Demand_Source
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:14"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Demand_PeriodLength
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:15"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Number_ofDemand_Periods
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:16"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Forced_DemandSync_Delay
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:17"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Unit_Error_Action
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:18"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Software_ErrorLog_Full_Action
  Type: MicroControllerTag
  DataType: Float
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "F11:19"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
