Name: DateAndTimeConfiguration
Type: FolderType
Children:
- Name: Table_Password
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:0"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Date_Year
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:1"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Date_Month
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:2"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Date_Day
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:3"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Hour
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:4"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Minute
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:5"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Seconds
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:6"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
- Name: Time_Hundredths
  Type: MicroControllerTag
  DataType: Int32
  Children:
  - Name: SymbolName
    Type: BaseDataVariableType
    DataType: String
    Value: "N14:7"
  - Name: ArrayUpdateMode
    Type: BaseDataVariableType
    DataType: TagArrayUpdateMode
    ModellingRule: Optional
